### ISSUE TITLE
How to use this w/ Apache License?

### ISSUE THREAD

**Issue by chiefy** [mrkjffrsn/RokuFramework#19]
Sorry, maybe I am missing something but what's the idea with this being a Framework if you have to document/note all code changes (Apache 2.0)? Is the idea to fork it and then PR back w/o metadata? 

I am looking to create my own Roku channel and would love to use this but not sure how that would work w/ the current license?

**Comment by mrkjffrsn** [comment]
@chiefy Thanks for considering to commit to this code base. Please feel free to fork and open a PR. Would love to look at what you've done.
